/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}',
  ],
  theme: {
    extend: {
      colors: {
        ink: '#171717',
        'on-primary': '#ffffff',
        body: '#4d4d4d',
        mute: '#8f8f8f',
        faint: '#a1a1a1',
        hairline: '#ebebeb',
        'hairline-soft': '#f2f2f2',
        canvas: '#fafafa',
        'canvas-elevated': '#ffffff',
        link: '#0070f3',
        'link-deep': '#0761d1',
        'link-soft': '#d3e5ff',
        error: '#ee0000',
        'error-deep': '#c50000',
        warning: '#f5a623',
        'warning-soft': '#ffefcf',
        'warning-deep': '#ab570a',
        violet: '#7928ca',
        'violet-soft': '#d8ccf1',
        cyan: '#50e3c2',
        'cyan-soft': '#aaffec',
        pink: '#ff0080',
        magenta: '#eb367f',
      },
      fontFamily: {
        sans: ['Geist', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['Geist Mono', 'JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'display-xl': ['48px', { lineHeight: '48px', letterSpacing: '-2.4px', fontWeight: '600' }],
        'heading-lg': ['32px', { lineHeight: '40px', letterSpacing: '-1.28px', fontWeight: '600' }],
        'heading-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.4px', fontWeight: '600' }],
        'label-sm': ['14px', { lineHeight: '20px', letterSpacing: '-0.28px', fontWeight: '500' }],
        'mono-eyebrow': ['12px', { lineHeight: '16px', letterSpacing: '0', fontWeight: '500', textTransform: 'uppercase' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', letterSpacing: '0', fontWeight: '400' }],
        'button-lg': ['16px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '500' }],
        'button-md': ['14px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '500' }],
        'code': ['14px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '400' }],
      },
      borderRadius: {
        'none': '0px',
        'sm': '6px',
        'md': '12px',
        'lg': '16px',
        'pill-category': '64px',
        'pill': '100px',
        'full': '9999px',
      },
      spacing: {
        'xxs': '4px',
        'xs': '8px',
        'sm': '12px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        '2xl': '40px',
        '3xl': '64px',
        '4xl': '96px',
        'section': '128px',
      },
      boxShadow: {
        'whisper': '0px 1px 1px rgba(0,0,0,0.04)',
        'floating': '0px 2px 2px rgba(0,0,0,0.04), 0px 8px 16px -4px rgba(0,0,0,0.04)',
      },
      transitionDuration: {
        'fast': '150ms',
        'normal': '200ms',
        'slow': '300ms',
      },
      transitionTimingFunction: {
        'ease-out': 'cubic-bezier(0.25, 0.46, 0.45, 0.94)',
      },
    },
  },
  plugins: [],
};