/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        ink: 'var(--color-text)',
        'on-primary': 'var(--color-on-primary)',
        body: 'var(--color-text-body)',
        mute: 'var(--color-text-mute)',
        faint: 'var(--color-text-faint)',
        hairline: 'var(--color-border)',
        'hairline-soft': 'var(--color-border-soft)',
        canvas: 'var(--color-bg)',
        'canvas-elevated': 'var(--color-bg-elevated)',
        link: 'var(--color-primary)',
        'link-deep': 'var(--color-primary)',
        'link-soft': 'var(--color-border-soft)',
        error: 'var(--color-text)',
        'error-deep': 'var(--color-text)',
        'error-soft': 'var(--color-border-soft)',
        warning: 'var(--color-text)',
        'warning-soft': 'var(--color-border-soft)',
        'warning-deep': 'var(--color-text)',
        success: 'var(--color-text)',
        'success-soft': 'var(--color-border-soft)',
        violet: 'var(--color-text)',
        'violet-soft': 'var(--color-border-soft)',
        cyan: 'var(--color-text)',
        'cyan-soft': 'var(--color-border-soft)',
        pink: 'var(--color-text)',
        magenta: 'var(--color-text)',
      },
      fontFamily: {
        sans: ['"Space Grotesk"', 'Inter', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'monospace'],
      },
      fontSize: {
        'display-xl': ['48px', { lineHeight: '1', letterSpacing: '-0.05em', fontWeight: '600' }],
        'display-lg': ['36px', { lineHeight: '1.05', letterSpacing: '-0.04em', fontWeight: '600' }],
        'heading-lg': ['28px', { lineHeight: '1.25', letterSpacing: '-0.03em', fontWeight: '600' }],
        'heading-md': ['20px', { lineHeight: '1.4', letterSpacing: '-0.02em', fontWeight: '600' }],
        'heading-sm': ['16px', { lineHeight: '1.4', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-sm': ['13px', { lineHeight: '1.43', letterSpacing: '-0.01em', fontWeight: '500' }],
        'mono-eyebrow': ['11px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '1.43', letterSpacing: '0', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'button-lg': ['14px', { lineHeight: '1', letterSpacing: '-0.01em', fontWeight: '500' }],
        'button-md': ['13px', { lineHeight: '1', letterSpacing: '-0.01em', fontWeight: '500' }],
        'code': ['13px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
      },
      borderRadius: {
        'none': '0px',
        'sm': '6px',
        'md': '10px',
        'lg': '14px',
        'xl': '20px',
        'pill': '9999px',
        'full': '9999px',
      },
      spacing: {
        'xxs': '4px',
        'xs': '8px',
        'sm': '12px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        '2xl': '40px',
        '3xl': '64px',
        '4xl': '96px',
        'section': '128px',
      },
      boxShadow: {
        'whisper': '0 0 0 1px var(--color-border-soft), 0 1px 3px var(--color-shadow)',
        'floating': '0 0 0 1px var(--color-border-soft), 0 8px 32px var(--color-shadow)',
        'glow': '0 0 0 1px var(--color-border), 0 0 24px var(--color-shadow)',
        'inner-top': 'inset 0 1px 0 var(--color-border-soft)',
      },
      transitionDuration: {
        'fast': '120ms',
        'normal': '200ms',
        'slow': '350ms',
      },
      transitionTimingFunction: {
        'smooth': 'cubic-bezier(0.25, 0.46, 0.45, 0.94)',
      },
      keyframes: {
        'slide-up': {
          from: { opacity: '0', transform: 'translateY(10px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-down': {
          from: { opacity: '0', transform: 'translateY(-6px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        'expand-down': {
          from: { opacity: '0', maxHeight: '0', transform: 'translateY(-4px)' },
          to: { opacity: '1', maxHeight: '2000px', transform: 'translateY(0)' },
        },
        'pulse-glow': {
          '0%, 100%': { opacity: '0.3' },
          '50%': { opacity: '0.7' },
        },
      },
      animation: {
        'slide-up': 'slide-up 0.2s cubic-bezier(0.25, 0.46, 0.45, 0.94)',
        'slide-down': 'slide-down 0.2s cubic-bezier(0.25, 0.46, 0.45, 0.94)',
        'fade-in': 'fade-in 0.15s ease-out',
        'expand-down': 'expand-down 0.25s cubic-bezier(0.25, 0.46, 0.45, 0.94)',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
