/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Light mode (default)
        ink: '#071c2f',
        'on-primary': '#ffffff',
        body: '#315357',
        mute: '#668487',
        faint: '#8aa5a5',
        hairline: '#c8ddd8',
        'hairline-soft': '#e4f1ec',
        canvas: '#f3faf6',
        'canvas-elevated': '#ffffff',
        link: '#176b63',
        'link-deep': '#0c514d',
        'link-soft': '#d4efe4',
        error: '#b43d3d',
        'error-deep': '#8e2727',
        warning: '#8b6818',
        'warning-soft': '#f8edc9',
        'warning-deep': '#6e5111',
        violet: '#4d7773',
        'violet-soft': '#d9e9e3',
        cyan: '#071c2f',
        'cyan-soft': '#b9e8d4',
        pink: '#79b9a6',
        magenta: '#3f7773',

        // Dark mode overrides
        'dark-ink': '#bef3d9',
        'dark-on-primary': '#071c2f',
        'dark-body': '#c7ddd7',
        'dark-mute': '#89aaa5',
        'dark-faint': '#62837f',
        'dark-hairline': '#28504e',
        'dark-hairline-soft': '#173c3d',
        'dark-canvas': '#071c2f',
        'dark-canvas-elevated': '#0d2939',
        'dark-link': '#bef3d9',
        'dark-link-deep': '#8ce4c2',
        'dark-link-soft': '#174c4b',
        'dark-error': '#ff9c94',
        'dark-error-deep': '#ff706c',
        'dark-warning': '#f6d889',
        'dark-warning-soft': '#4b4330',
        'dark-warning-deep': '#e3bd5f',
        'dark-violet': '#8bb9b1',
        'dark-violet-soft': '#204b4b',
        'dark-cyan': '#bef3d9',
        'dark-cyan-soft': '#174c4b',
        'dark-pink': '#9bd9c7',
        'dark-magenta': '#4d8e87',
      },
      fontFamily: {
        sans: ['Manrope', 'Avenir Next', 'system-ui', 'sans-serif'],
        mono: ['IBM Plex Mono', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'display-xl': ['48px', { lineHeight: '48px', letterSpacing: '-2.4px', fontWeight: '600' }],
        'heading-lg': ['32px', { lineHeight: '40px', letterSpacing: '-1.28px', fontWeight: '600' }],
        'heading-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.4px', fontWeight: '600' }],
        'label-sm': ['14px', { lineHeight: '20px', letterSpacing: '-0.28px', fontWeight: '500' }],
        'mono-eyebrow': ['12px', { lineHeight: '16px', letterSpacing: '0', fontWeight: '500', textTransform: 'uppercase' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', letterSpacing: '0', fontWeight: '400' }],
        'button-lg': ['16px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '500' }],
        'button-md': ['14px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '500' }],
        'code': ['14px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '400' }],
      },
      borderRadius: {
        'none': '0px',
        'sm': '6px',
        'md': '12px',
        'lg': '16px',
        'pill-category': '64px',
        'pill': '100px',
        'full': '9999px',
      },
      spacing: {
        'xxs': '4px',
        'xs': '8px',
        'sm': '12px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        '2xl': '40px',
        '3xl': '64px',
        '4xl': '96px',
        'section': '128px',
      },
      boxShadow: {
        'whisper': '0px 1px 1px rgba(0,0,0,0.04)',
        'floating': '0px 2px 2px rgba(0,0,0,0.04), 0px 8px 16px -4px rgba(0,0,0,0.04)',
        'dark-whisper': '0px 1px 1px rgba(255,255,255,0.04)',
        'dark-floating': '0px 2px 2px rgba(255,255,255,0.04), 0px 8px 16px -4px rgba(255,255,255,0.04)',
      },
      transitionDuration: {
        'fast': '150ms',
        'normal': '200ms',
        'slow': '300ms',
      },
      transitionTimingFunction: {
        'ease-out': 'cubic-bezier(0.25, 0.46, 0.45, 0.94)',
      },
    },
  },
  plugins: [],
};